name: Auto-approve low priority PRs

on:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: company-z/github-actions/.github/actions/auto-approve@main