name: PR Priority Label Check

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  check-priority-label:
    name: Check Priority Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: company-z/github-actions/.github/actions/check-labels@main

